export const userData = [
  {
    id: 1,
    name: "Abdur Rahim",
    username: "arahim",
    email: "rahim@example.com",
    role: "Admin",
    phone: "+8801700123456",
    website: "rahim.dev",
    address: {
      street: "House 12, Road 5, Mirpur DOHS",
      city: "Dhaka",
      zip: "1216",
    },
    company: {
      name: "Tech Bangla",
      position: "Senior Developer",
    },
    image: "https://i.pravatar.cc/150?u=1",
    description: "Expert in React and Next.js with 5 years of experience.",
  },
  {
    id: 2,
    name: "Sumaiya Akter",
    username: "sumaiya_a",
    email: "sumaiya@example.com",
    role: "User",
    phone: "+8801800987654",
    website: "sumaiya.design",
    address: {
      street: "Flat 4B, Gulshan Avenue",
      city: "Dhaka",
      zip: "1212",
    },
    company: {
      name: "Creative IT",
      position: "UI/UX Designer",
    },
    image: "https://i.pravatar.cc/150?u=2",
    description: "Passionate designer focusing on accessible web interfaces.",
  },
  {
    id: 3,
    name: "Hasan Mahmud",
    username: "hasan_m",
    email: "hasan@example.com",
    role: "Editor",
    phone: "+8801900112233",
    website: "hasanblogs.com",
    address: {
      street: "Agrabad C/A",
      city: "Chittagong",
      zip: "4100",
    },
    company: {
      name: "News 24",
      position: "Content Writer",
    },
    image: "https://i.pravatar.cc/150?u=3",
    description: "Writes technical articles and documentation.",
  },
  {
    id: 4,
    name: "Fatima Begum",
    username: "fatima_b",
    email: "fatima@example.com",
    role: "User",
    phone: "+8801600554433",
    website: "fatima.store",
    address: {
      street: "Zindabazar",
      city: "Sylhet",
      zip: "3100",
    },
    company: {
      name: "E-Shop Sylhet",
      position: "Manager",
    },
    image: "https://i.pravatar.cc/150?u=4",
    description: "Managing local e-commerce operations efficiently.",
  },
  {
    id: 5,
    name: "Kamal Hossain",
    username: "kamal_h",
    email: "kamal@example.com",
    role: "User",
    phone: "+8801500778899",
    website: "kamal.tech",
    address: {
      street: "Padma Residential Area",
      city: "Rajshahi",
      zip: "6000",
    },
    company: {
      name: "Silk Valley",
      position: "Backend Dev",
    },
    image: "https://i.pravatar.cc/150?u=5",
    description: "Backend specialist loving Node.js and Python.",
  },
  {
    id: 6,
    name: "Nusrat Jahan",
    username: "nusrat_j",
    email: "nusrat@example.com",
    role: "Admin",
    phone: "+8801300223344",
    website: "nusrat.io",
    address: {
      street: "Khulna Shipyard Road",
      city: "Khulna",
      zip: "9000",
    },
    company: {
      name: "SoftBD",
      position: "CTO",
    },
    image: "https://i.pravatar.cc/150?u=6",
    description: "Leading the technology team with vision.",
  },
  {
    id: 7,
    name: "Rafiqul Islam",
    username: "rafiq_i",
    email: "rafiq@example.com",
    role: "User",
    phone: "+8801700667788",
    website: "rafiq.me",
    address: {
      street: "College Road",
      city: "Barisal",
      zip: "8200",
    },
    company: {
      name: "River Tech",
      position: "Full Stack Dev",
    },
    image: "https://i.pravatar.cc/150?u=7",
    description: "Building scalable web applications.",
  },
  {
    id: 8,
    name: "Tasnim Fariha",
    username: "tasnim_f",
    email: "tasnim@example.com",
    role: "User",
    phone: "+8801800445566",
    website: "tasnim.art",
    address: {
      street: "Town Hall",
      city: "Mymensingh",
      zip: "2200",
    },
    company: {
      name: "Art House",
      position: "Graphic Designer",
    },
    image: "https://i.pravatar.cc/150?u=8",
    description: "Creating visual concepts to inspire and captivate.",
  },
  {
    id: 9,
    name: "Imran Khan",
    username: "imran_k",
    email: "imran@example.com",
    role: "Editor",
    phone: "+8801900889900",
    website: "imran.news",
    address: {
      street: "Station Road",
      city: "Rangpur",
      zip: "5400",
    },
    company: {
      name: "Daily Rangpur",
      position: "Journalist",
    },
    image: "https://i.pravatar.cc/150?u=9",
    description: "Reporting on tech trends and local startups.",
  },
  {
    id: 10,
    name: "Sadia Afrin",
    username: "sadia_a",
    email: "sadia@example.com",
    role: "User",
    phone: "+8801600112299",
    website: "sadia.code",
    address: {
      street: "Cox's Bazar Main Rd",
      city: "Cox's Bazar",
      zip: "4700",
    },
    company: {
      name: "Beach IT",
      position: "Frontend Dev",
    },
    image: "https://i.pravatar.cc/150?u=10",
    description: "Frontend developer with a love for animations.",
  },
];
