import type { Metadata } from "next";
import AuthProvider from "@/app/Provider/userSate";

import "./globals.css";
import Header from "./components/Header";

export const metadata: Metadata = {
  title: "Create user App",
  description: "Generated by create user app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <Header />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
